### PR TITLE
add LAYERSERIES_COMPAT_laird-cp for thud

### PR DESCRIPTION
**Pull request by martingraebner**
see
https://www.yoctoproject.org/docs/3.1/ref-manual/ref-manual.html#var-LAYERSERIES_COMPAT

### CODE REVIEW

**Comment by borkra** [comment]
The proposed change will disable the layer for other releases like: sumo, warrior, zeus, dunfell, etc. that people are using.

Better live with the warning during build then maintain endless list possible releases.

**Comment by skycaptain** [comment]
@borkra `LAYERSERIES_COMPAT` is mandatory according to Yocto's Documentation: https://www.yoctoproject.org/docs/latest/ref-manual/ref-manual.html#var-LAYERSERIES_COMPAT

However a list is also allowed. For example see the layer.conf of meta-swupdate: https://github.com/sbabic/meta-swupdate/blob/320e65011b5e6a42f71ef4ec4f69822faa87e38c/conf/layer.conf#L12

**Comment by borkra** [comment]
Yes, I agree list is allowed, but the problem is that when new version released and LAYERSERIES_COMPAT variable exist, Yocto does not just issue the warning, it just refuses to use the layer all together. At least that how it worked before. And that is down right unacceptable, we prefer not have obligation to monitor Yocto releases, and update the variable every time new release comes out.

**Comment by DavidNorrisBB** [comment]
Would you reconsider this PR? I think @skycaptain is correct: this variable is **mandatory**, plain and simple. I understand your concern about maintenance, but that concern would better be addressed upstream to the Yocto / OE team... the fact is it's mandatory, and without it this layer is not compliant with the Yocto Project Compatible Specification. Other vendors provide this in their layers. Thanks.

**Comment by borkra** [comment]
No you are incorrect, this variable is not mandatory. Without it user just get a warning, that he can ignore. We do use this layer internally, upto mickledore, and everything works great without this variable.

Our Wi-Fi radio releases do support all  kernels versions from 3.0 up and as such all Yocto releases for that period.
Testing every Yocto release for every our release is cost prohibitive, as such compatibility with any particular Yocto version is expected, but not guaranteed. 

This layer has the example status, it is expected that user should take this layer and do whatever. If there is an issue he can report an issue through our tech support channel, and we will fix it.

Other vendors do not support that variety of host systems and versions, we are pretty much the only one that does.

**Pull request closed without merging**
